[package]
name = "in-one-weekend"
version = "0.1.0"
authors = ["Antony Lesage <lesage.antony@gmail.com>"]
edition = "2018"

[dependencies]
derive-new = "0.5"
itertools = "0.7"
nalgebra = "0.16"
png = "0.13"
rand = "0.6"
rayon = "1.0"
structopt = "0.2"
